language: android

android:
  components:
    - build-tools-29.0.3

before_cache:
  # Gradle creates lock files on every run which makes the cache "different" for every build
  - find ~/.gradle/caches/ -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.gradle/caches/

script:
  - ./gradlew check jacocoTestReport japicmp

after_success:
  - bash <(curl -s https://codecov.io/bash)
